apiVersion: v1
kind: ConfigMap
metadata:
  name: svghunt0-config
  labels:
    app.kubernetes.io/name: svghunt0
data:
  INSTANCE_DOMAIN: "api.topia.io"
  INSTANCE_PROTOCOL: "https"
  INTERACTIVE_KEY: "mHag8ZZeMT3uA506wrNl"
  NODE_ENV: "production"
  PORT: "3000"
  S3_BUCKET: "sdk-scavenger-hunt"
